require('./app.js');
//controlers
require('./controllers/appController.js');
require('./controllers/attributesController.js');
require('./controllers/componentsController.js')
require('./controllers/capabilitiesController.js');
require('./controllers/projectsListController.js');
//directives
require('./directives/capabilities/capabilitiesDir.js')
require('./directives/att&comp/attAndComp.js')
require('./directives/projectTable/projectTable.js')
require('./directives/sidebar/sidebar.js')
